### ISSUE TITLE
Add media not work correctly

### ISSUE THREAD

**Issue by antoniorodc** [t-hamano/custom-html-block-extension#73] opened 2023-07-28 05:58 UTC
Hi,

This issue is similar to [this one](https://github.com/t-hamano/custom-html-block-extension/issues/68).

When I click the "Add Media" button and choose some image or file uploaded, the text in the window doesn't update. I have to switch to the "Visual Editor" tab and then the text appears. That is, the text is inserted but not displayed in the "Html" tab until I change the tab.

Regards.

**Comment by t-hamano** [comment] 2023-07-28 12:23
Thanks for the report.

I have not been able to test it yet, but if I can reproduce it, I will consider fixing it in the next update.

**Comment by antoniorodc** [comment] 2023-08-02 05:44
Hi,

Just to comment that this problem only occurs when the first link is inserted. After that it works fine, or if the <a> tag already exists in the text, it works fine too. I hope it helps you to solve it.

**Comment by t-hamano** [comment] 2023-08-17 04:07
I could not reproduce it. Could you please stop all other plugins and test once?

https://github.com/t-hamano/custom-html-block-extension/assets/54422211/af3edd41-cd21-49b7-8864-519957ebece8

**Comment by antoniorodc** [comment] 2023-08-17 08:48
Indeed, it works correctly that way. Try typing a text before adding the media and then you will see the problem. In the "Text" tab nothing appears, but if you switch to the "Visual" tab the link appears.

**Comment by t-hamano** [comment] 2023-08-17 10:58
Well, I did indeed reproduce it. I will try to find the cause.


https://github.com/t-hamano/custom-html-block-extension/assets/54422211/df165deb-a5db-4c80-ae1d-75550fc69587

**Comment by t-hamano** [comment] 2023-10-19 14:21
Hi,

I think this problem could probably be fixed with 9cd69c6. We plan to release a new version that includes this fix by the release of WordPress 6.4, so please try again when it is released.

**Closed by t-hamano** 2023-10-19 14:21 UTC
Labels: bug, Release for WP6.4
