### ISSUE TITLE
“Add link” form/popup breaks with Custom HTML Block Extension

### ISSUE THREAD

**Issue by rghedin** [t-hamano/custom-html-block-extension#68] opened 2023-04-12 16:40 UTC
Hi!

When I click in the add link button, focus is kept “behind” the popup form, so I can't paste links nor hit `Enter` to confirm the link added.

I recorded a short video showing the issue:

https://user-images.githubusercontent.com/19216581/231524607-8f14fd5c-3e12-4e8c-b90a-8a3982ffd842.mp4

**Comment by t-hamano** [comment] 2023-04-15 02:14
Thanks for the report. But I was not able to reproduce it.

I would appreciate it if you could check the following:

- What is your WordPress version? (I tested on WordPress 6.2)
- Does it reproduce when you switch to the default theme and activate only this plugin and the classic editor plugin?
- Does it also happen when you reset the settings of this plugin to default? (It would be a good idea to export the settings from the Tools menu before resetting)


https://user-images.githubusercontent.com/54422211/232178155-282020a0-b435-4735-86d8-1833fa4a628b.mp4

**Comment by t-hamano** [comment] 2023-10-19 14:23
I'm still not sure of the complete steps to reproduce this problem, so I'm going to remove the WP6.4 label.

**Comment by t-hamano** [comment] 2024-06-26 04:41
I am closing this issue because I cannot reproduce this problem in any way. If you have a complete procedure to reproduce it, please comment.

**Closed by t-hamano** 2024-06-26 04:41 UTC
Labels: bug, classic-editor, Needs More Info
